# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  # username: ENV["username"]
#   password:
  host: localhost
  port: 5432
    
development: 
  database: yayasan_yakin_development
  username: ENV["database_username"]
  password: 
  <<: *defaults 

production:
  database: yayasan_yakin_production
  username: ENV["database_username"]
  password: ENV["database_password"]
  

# test: &test
#   database: yayasan_yakin_test
#   <<: *defaults

# production:  
#   database: contact_book_production
#   <<: *defaults 


# Error running './configure --prefix=/Users/macbook/.rvm/rubies/ruby-2.0.0-p645  --with-opt-dir=/usr/local/opt/libyaml:/usr/local/opt/readline:/usr/local/opt/libksba:/usr/local/opt/openssl --without-tcl --without-tk --disable-install-doc --enable-shared',
# showing last 15 lines of /Users/macbook/.rvm/log/1432481573_ruby-2.0.0-p645/configure.log

# rvm reinstall ruby-2.2.0 --with-openssl-dir=/path/to/openssl